# Generated by Django 5.2.8 on 2025-11-16 19:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transport_type', models.CharField(choices=[('bus', 'Bus'), ('flight', 'Flight'), ('train', 'Train'), ('boat', 'Boat')], default='bus', max_length=30)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(max_length=2048)),
                ('origin', models.CharField(choices=[('NG-ZA', 'Zamfara'), ('NG-KT', 'Katsina'), ('NG-CR', 'Cross River'), ('NG-KW', 'Kwara'), ('NG-DE', 'Delta'), ('NG-LA', 'Lagos'), ('NG-EB', 'Ebonyi'), ('NG-NA', 'Nasarawa'), ('NG-ED', 'Edo'), ('NG-NI', 'Niger'), ('NG-EK', 'Ekiti'), ('NG-OG', 'Ogun'), ('NG-EN', 'Enugu'), ('NG-ON', 'Ondo'), ('NG-AB', 'Abia'), ('NG-FC', 'Abuja Federal Capital Territory'), ('NG-OS', 'Osun'), ('NG-GO', 'Gombe'), ('NG-AD', 'Adamawa'), ('NG-OY', 'Oyo'), ('NG-IM', 'Imo'), ('NG-AK', 'Akwa Ibom'), ('NG-PL', 'Plateau'), ('NG-JI', 'Jigawa'), ('NG-AN', 'Anambra'), ('NG-RI', 'Rivers'), ('NG-KD', 'Kaduna'), ('NG-BA', 'Bauchi'), ('NG-SO', 'Sokoto'), ('NG-KE', 'Kebbi'), ('NG-BE', 'Benue'), ('NG-TA', 'Taraba'), ('NG-KN', 'Kano'), ('NG-BO', 'Borno'), ('NG-YO', 'Yobe'), ('NG-KO', 'Kogi'), ('NG-BY', 'Bayelsa')], default='NG-LA', max_length=50)),
                ('destination', models.CharField(choices=[('NG-ZA', 'Zamfara'), ('NG-KT', 'Katsina'), ('NG-CR', 'Cross River'), ('NG-KW', 'Kwara'), ('NG-DE', 'Delta'), ('NG-LA', 'Lagos'), ('NG-EB', 'Ebonyi'), ('NG-NA', 'Nasarawa'), ('NG-ED', 'Edo'), ('NG-NI', 'Niger'), ('NG-EK', 'Ekiti'), ('NG-OG', 'Ogun'), ('NG-EN', 'Enugu'), ('NG-ON', 'Ondo'), ('NG-AB', 'Abia'), ('NG-FC', 'Abuja Federal Capital Territory'), ('NG-OS', 'Osun'), ('NG-GO', 'Gombe'), ('NG-AD', 'Adamawa'), ('NG-OY', 'Oyo'), ('NG-IM', 'Imo'), ('NG-AK', 'Akwa Ibom'), ('NG-PL', 'Plateau'), ('NG-JI', 'Jigawa'), ('NG-AN', 'Anambra'), ('NG-RI', 'Rivers'), ('NG-KD', 'Kaduna'), ('NG-BA', 'Bauchi'), ('NG-SO', 'Sokoto'), ('NG-KE', 'Kebbi'), ('NG-BE', 'Benue'), ('NG-TA', 'Taraba'), ('NG-KN', 'Kano'), ('NG-BO', 'Borno'), ('NG-YO', 'Yobe'), ('NG-KO', 'Kogi'), ('NG-BY', 'Bayelsa')], default='NG-CR', max_length=50)),
                ('departure_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.PositiveIntegerField()),
                ('total_seats', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(max_length=128)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=128)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('num_seats', models.PositiveIntegerField()),
                ('booking_date', models.DateTimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.listing')),
            ],
            options={
                'unique_together': {('listing', 'passenger_name', 'passenger_email')},
            },
        ),
    ]
