# Generated by Django 5.2.8 on 2025-11-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='listing',
            name='destination',
            field=models.CharField(choices=[('NG-KO', 'Kogi'), ('NG-BY', 'Bayelsa'), ('NG-YO', 'Yobe'), ('NG-KT', 'Katsina'), ('NG-CR', 'Cross River'), ('NG-ZA', 'Zamfara'), ('NG-KW', 'Kwara'), ('NG-DE', 'Delta'), ('NG-LA', 'Lagos'), ('NG-EB', 'Ebonyi'), ('NG-NA', 'Nasarawa'), ('NG-ED', 'Edo'), ('NG-NI', 'Niger'), ('NG-EK', 'Ekiti'), ('NG-OG', 'Ogun'), ('NG-EN', 'Enugu'), ('NG-ON', 'Ondo'), ('NG-AB', 'Abia'), ('NG-FC', 'Abuja Federal Capital Territory'), ('NG-OS', 'Osun'), ('NG-GO', 'Gombe'), ('NG-AD', 'Adamawa'), ('NG-OY', 'Oyo'), ('NG-IM', 'Imo'), ('NG-AK', 'Akwa Ibom'), ('NG-PL', 'Plateau'), ('NG-JI', 'Jigawa'), ('NG-AN', 'Anambra'), ('NG-RI', 'Rivers'), ('NG-KD', 'Kaduna'), ('NG-BA', 'Bauchi'), ('NG-SO', 'Sokoto'), ('NG-KE', 'Kebbi'), ('NG-BE', 'Benue'), ('NG-TA', 'Taraba'), ('NG-KN', 'Kano'), ('NG-BO', 'Borno')], default='NG-CR', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='origin',
            field=models.CharField(choices=[('NG-KO', 'Kogi'), ('NG-BY', 'Bayelsa'), ('NG-YO', 'Yobe'), ('NG-KT', 'Katsina'), ('NG-CR', 'Cross River'), ('NG-ZA', 'Zamfara'), ('NG-KW', 'Kwara'), ('NG-DE', 'Delta'), ('NG-LA', 'Lagos'), ('NG-EB', 'Ebonyi'), ('NG-NA', 'Nasarawa'), ('NG-ED', 'Edo'), ('NG-NI', 'Niger'), ('NG-EK', 'Ekiti'), ('NG-OG', 'Ogun'), ('NG-EN', 'Enugu'), ('NG-ON', 'Ondo'), ('NG-AB', 'Abia'), ('NG-FC', 'Abuja Federal Capital Territory'), ('NG-OS', 'Osun'), ('NG-GO', 'Gombe'), ('NG-AD', 'Adamawa'), ('NG-OY', 'Oyo'), ('NG-IM', 'Imo'), ('NG-AK', 'Akwa Ibom'), ('NG-PL', 'Plateau'), ('NG-JI', 'Jigawa'), ('NG-AN', 'Anambra'), ('NG-RI', 'Rivers'), ('NG-KD', 'Kaduna'), ('NG-BA', 'Bauchi'), ('NG-SO', 'Sokoto'), ('NG-KE', 'Kebbi'), ('NG-BE', 'Benue'), ('NG-TA', 'Taraba'), ('NG-KN', 'Kano'), ('NG-BO', 'Borno')], default='NG-LA', max_length=50),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='listings_us_email_c12c68_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
