# Generated by Django 6.0 on 2026-01-04 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_user_options_alter_listing_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='destination',
            field=models.CharField(choices=[('NG-ON', 'Ondo'), ('NG-AB', 'Abia'), ('NG-FC', 'Abuja Federal Capital Territory'), ('NG-OS', 'Osun'), ('NG-GO', 'Gombe'), ('NG-AD', 'Adamawa'), ('NG-OY', 'Oyo'), ('NG-IM', 'Imo'), ('NG-AK', 'Akwa Ibom'), ('NG-PL', 'Plateau'), ('NG-JI', 'Jigawa'), ('NG-AN', 'Anambra'), ('NG-RI', 'Rivers'), ('NG-KD', 'Kaduna'), ('NG-BA', 'Bauchi'), ('NG-SO', 'Sokoto'), ('NG-KE', 'Kebbi'), ('NG-BE', 'Benue'), ('NG-TA', 'Taraba'), ('NG-KN', 'Kano'), ('NG-BO', 'Borno'), ('NG-YO', 'Yobe'), ('NG-KO', 'Kogi'), ('NG-BY', 'Bayelsa'), ('NG-ZA', 'Zamfara'), ('NG-KT', 'Katsina'), ('NG-CR', 'Cross River'), ('NG-KW', 'Kwara'), ('NG-DE', 'Delta'), ('NG-LA', 'Lagos'), ('NG-EB', 'Ebonyi'), ('NG-NA', 'Nasarawa'), ('NG-ED', 'Edo'), ('NG-NI', 'Niger'), ('NG-EK', 'Ekiti'), ('NG-OG', 'Ogun'), ('NG-EN', 'Enugu')], default='NG-CR', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='origin',
            field=models.CharField(choices=[('NG-ON', 'Ondo'), ('NG-AB', 'Abia'), ('NG-FC', 'Abuja Federal Capital Territory'), ('NG-OS', 'Osun'), ('NG-GO', 'Gombe'), ('NG-AD', 'Adamawa'), ('NG-OY', 'Oyo'), ('NG-IM', 'Imo'), ('NG-AK', 'Akwa Ibom'), ('NG-PL', 'Plateau'), ('NG-JI', 'Jigawa'), ('NG-AN', 'Anambra'), ('NG-RI', 'Rivers'), ('NG-KD', 'Kaduna'), ('NG-BA', 'Bauchi'), ('NG-SO', 'Sokoto'), ('NG-KE', 'Kebbi'), ('NG-BE', 'Benue'), ('NG-TA', 'Taraba'), ('NG-KN', 'Kano'), ('NG-BO', 'Borno'), ('NG-YO', 'Yobe'), ('NG-KO', 'Kogi'), ('NG-BY', 'Bayelsa'), ('NG-ZA', 'Zamfara'), ('NG-KT', 'Katsina'), ('NG-CR', 'Cross River'), ('NG-KW', 'Kwara'), ('NG-DE', 'Delta'), ('NG-LA', 'Lagos'), ('NG-EB', 'Ebonyi'), ('NG-NA', 'Nasarawa'), ('NG-ED', 'Edo'), ('NG-NI', 'Niger'), ('NG-EK', 'Ekiti'), ('NG-OG', 'Ogun'), ('NG-EN', 'Enugu')], default='NG-LA', max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_ref', models.CharField(max_length=255, unique=True)),
                ('chapa_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='listings.booking')),
            ],
        ),
    ]
