# Generated by Django 6.0 on 2026-01-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_destination_alter_listing_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='destination',
            field=models.CharField(choices=[('NG-DE', 'Delta'), ('NG-LA', 'Lagos'), ('NG-EB', 'Ebonyi'), ('NG-NA', 'Nasarawa'), ('NG-ED', 'Edo'), ('NG-NI', 'Niger'), ('NG-EK', 'Ekiti'), ('NG-OG', 'Ogun'), ('NG-EN', 'Enugu'), ('NG-ON', 'Ondo'), ('NG-AB', 'Abia'), ('NG-FC', 'Abuja Federal Capital Territory'), ('NG-OS', 'Osun'), ('NG-GO', 'Gombe'), ('NG-AD', 'Adamawa'), ('NG-OY', 'Oyo'), ('NG-IM', 'Imo'), ('NG-AK', 'Akwa Ibom'), ('NG-PL', 'Plateau'), ('NG-JI', 'Jigawa'), ('NG-AN', 'Anambra'), ('NG-RI', 'Rivers'), ('NG-KD', 'Kaduna'), ('NG-BA', 'Bauchi'), ('NG-SO', 'Sokoto'), ('NG-KE', 'Kebbi'), ('NG-BE', 'Benue'), ('NG-TA', 'Taraba'), ('NG-KN', 'Kano'), ('NG-BO', 'Borno'), ('NG-YO', 'Yobe'), ('NG-KO', 'Kogi'), ('NG-BY', 'Bayelsa'), ('NG-ZA', 'Zamfara'), ('NG-KT', 'Katsina'), ('NG-CR', 'Cross River'), ('NG-KW', 'Kwara')], default='NG-CR', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='origin',
            field=models.CharField(choices=[('NG-DE', 'Delta'), ('NG-LA', 'Lagos'), ('NG-EB', 'Ebonyi'), ('NG-NA', 'Nasarawa'), ('NG-ED', 'Edo'), ('NG-NI', 'Niger'), ('NG-EK', 'Ekiti'), ('NG-OG', 'Ogun'), ('NG-EN', 'Enugu'), ('NG-ON', 'Ondo'), ('NG-AB', 'Abia'), ('NG-FC', 'Abuja Federal Capital Territory'), ('NG-OS', 'Osun'), ('NG-GO', 'Gombe'), ('NG-AD', 'Adamawa'), ('NG-OY', 'Oyo'), ('NG-IM', 'Imo'), ('NG-AK', 'Akwa Ibom'), ('NG-PL', 'Plateau'), ('NG-JI', 'Jigawa'), ('NG-AN', 'Anambra'), ('NG-RI', 'Rivers'), ('NG-KD', 'Kaduna'), ('NG-BA', 'Bauchi'), ('NG-SO', 'Sokoto'), ('NG-KE', 'Kebbi'), ('NG-BE', 'Benue'), ('NG-TA', 'Taraba'), ('NG-KN', 'Kano'), ('NG-BO', 'Borno'), ('NG-YO', 'Yobe'), ('NG-KO', 'Kogi'), ('NG-BY', 'Bayelsa'), ('NG-ZA', 'Zamfara'), ('NG-KT', 'Katsina'), ('NG-CR', 'Cross River'), ('NG-KW', 'Kwara')], default='NG-LA', max_length=50),
        ),
    ]
